{{- if and .Values.gateway.enabled .Values.gateway.hosts -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "pocket-id.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  {{- range .Values.gateway.hosts }}
    {{- $name := .host | replace "." "-" }}
  - name: {{ $name }}-http
    hostname: {{ .host }}
    port: {{ .httpPort | default 80 }}
    protocol: HTTP
    allowedRoutes:
        namespaces:
          from: Same # Only allows HTTPRoutes from this namespace to attach
  - name: {{ $name }}-https
    hostname: {{ .host }}
    port: {{ .httpsPort | default 443 }}
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: {{ .tlsSecretName | default (printf "%s-secret" $name) }}
    allowedRoutes:
      namespaces:
        from: Same
  {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "pocket-id.fullname" . }}-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
spec:
  hostnames:
  {{- range .Values.gateway.hosts }}
  - {{ .host }}
  {{- end }}
  parentRefs:
  {{- range .Values.gateway.hosts }}
  - name: {{ include "pocket-id.fullname" $ }}
    sectionName: {{ .host | replace "." "-" }}-https
  {{- end }}
  rules:
  - backendRefs:
    - name: {{ include "pocket-id.fullname" $ }}
      port: {{ $.Values.service.port }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "pocket-id.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
spec:
  hostnames:
  {{- range .Values.gateway.hosts }}
  - {{ .host }}
  {{- end }}
  parentRefs:
  {{- range .Values.gateway.hosts }}
  - name: {{ include "pocket-id.fullname" $ }}
    sectionName: {{ .host | replace "." "-" }}-http
  {{- end }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}
