{{- if and .Values.httproute.enabled .Values.httproute.hosts -}}
{{- if .Values.httproute.httpsParentRefs }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "pocket-id.fullname" . }}-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
 {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
  {{- toYaml .Values.httproute.hosts | nindent 4 }}
  parentRefs: 
  {{- toYaml .Values.httproute.httpsParentRefs | nindent 4 }}
  rules:
  - backendRefs:
    - name: {{ include "pocket-id.fullname" $ }}
      port: {{ $.Values.service.port }}
{{- end }}
{{- if .Values.httproute.httpParentRefs }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "pocket-id.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
 {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
  {{- toYaml .Values.httproute.hosts | nindent 4 }}
  parentRefs: 
  {{- toYaml .Values.httproute.httpParentRefs | nindent 4 }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}
{{- end }}
